name: Fetch Movie Data

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  fetch-movie-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 禁用默认的 GitHub Actions 身份验证

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install axios dotenv

      - name: Run the movie fetch script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          node scripts/fetch-movies.js

      - name: Commit and push the updated movie data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/CineEcho/echo.git
          git add data/movies.json
          git commit -m "Update movie data"
          git push origin main
